#
# SASS/SCSS
#
sass:
  sass_dir: _sass
  style: compressed

#
# Linter
#
html_proofer:
  ignore_urls:
    - "https://www.youtube.com/c/VaibhavJha"
    - "https://www.linkedin.com/in/dytcnn"
    - "https://github.com/vaiijha"
    - "https://twitter.com/dytcnn"

#
# Page-specific settings
#
# Default values for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # Default values for pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

#
# Site Author
#
author:
  name             : "Vaibhav Jha"
  avatar           : "/images/profile_photo.png"
  # ENHANCED: Updated bio to reflect current role at IISc
  bio              : "Research Associate - 2 at the Indian Institute ofScience (IISc), focusing on HPC for Quantum Computing and AI. Previously a Data Engineer at Epsilon."
  # ENHANCED: Updated location and employer
  location         : "Bengaluru, KA"
  employer         : "Indian Institute of Science (IISc)"
  uri              :
  email            : "vaijha22@gmail.com"
  googlescholar    : "https://scholar.google.com/citations?user=oAXEYToAAAAJ&hl=en" # ENHANCED: Added Google Scholar link
  facebook         :
  twitter          : "dytcnn"
  github           : "vaiijha"
  linkedin         : "dytcnn"
